package com.foya.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema="BT3500", name="FY_TB_LOOKUP_TYPE")
@IdClass(com.foya.model.FyTbLookupTypeId.class)
public class FyTbLookupType {
	@Basic
	@Column(name="CR_DATE", columnDefinition="DATE")
	private Date crDate;

	@Basic
	@Column(name="CR_USER", length=40)
	private String crUser;

	@Basic
	@Column(columnDefinition="DATE")
	private Date datestamp;

	@Basic
	@Column(nullable=false, length=200)
	private String dscr;

	@Id
	@Column(name="LOOKUP_TYPE", length=20)
	private String lookupType;

	@Basic
	@Column(length=40)
	private String userstamp;


	public FyTbLookupType() {
	}

	public FyTbLookupType(String lookupType) {
		this.lookupType = lookupType;
	}

	public Date getCrDate() {
		return crDate;
	}

	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	public String getCrUser() {
		return crUser;
	}

	public void setCrUser(String crUser) {
		this.crUser = crUser;
	}

	public Date getDatestamp() {
		return datestamp;
	}

	public void setDatestamp(Date datestamp) {
		this.datestamp = datestamp;
	}

	public String getDscr() {
		return dscr;
	}

	public void setDscr(String dscr) {
		this.dscr = dscr;
	}

	public String getLookupType() {
		return lookupType;
	}

	public void setLookupType(String lookupType) {
		this.lookupType = lookupType;
	}

	public String getUserstamp() {
		return userstamp;
	}

	public void setUserstamp(String userstamp) {
		this.userstamp = userstamp;
	}
}