package com.foya.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema="BT3500", name="FY_TB_LOOKUP_CDE")
@IdClass(com.foya.model.FyTbLookupCdeId.class)
public class FyTbLookupCde {
	@Basic
	@Column(name="CR_DATE", columnDefinition="DATE")
	private Date crDate;

	@Basic
	@Column(name="CR_USER", length=40)
	private String crUser;

	@Basic
	@Column(columnDefinition="DATE")
	private Date datestamp;

	@Basic
	@Column(nullable=false, length=200)
	private String dscr;

	@Id
	@Column(name="LOOKUP_CDE", length=40)
	private String lookupCde;

	@Id
	@Column(name="LOOKUP_TYPE", length=20)
	private String lookupType;

	@Basic
	@Column(length=40)
	private String userstamp;

	@Basic
	@Column(length=100)
	private String value1;

	@Basic
	@Column(length=100)
	private String value2;

	@Basic
	@Column(length=100)
	private String value3;

	@Basic
	@Column(length=100)
	private String value4;

	@Basic
	@Column(length=100)
	private String value5;


	public FyTbLookupCde() {
	}

	public FyTbLookupCde(String lookupCde, String lookupType) {
		this.lookupCde = lookupCde;
		this.lookupType = lookupType;
	}

	public Date getCrDate() {
		return crDate;
	}

	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	public String getCrUser() {
		return crUser;
	}

	public void setCrUser(String crUser) {
		this.crUser = crUser;
	}

	public Date getDatestamp() {
		return datestamp;
	}

	public void setDatestamp(Date datestamp) {
		this.datestamp = datestamp;
	}

	public String getDscr() {
		return dscr;
	}

	public void setDscr(String dscr) {
		this.dscr = dscr;
	}

	public String getLookupCde() {
		return lookupCde;
	}

	public void setLookupCde(String lookupCde) {
		this.lookupCde = lookupCde;
	}

	public String getLookupType() {
		return lookupType;
	}

	public void setLookupType(String lookupType) {
		this.lookupType = lookupType;
	}

	public String getUserstamp() {
		return userstamp;
	}

	public void setUserstamp(String userstamp) {
		this.userstamp = userstamp;
	}

	public String getValue1() {
		return value1;
	}

	public void setValue1(String value1) {
		this.value1 = value1;
	}

	public String getValue2() {
		return value2;
	}

	public void setValue2(String value2) {
		this.value2 = value2;
	}

	public String getValue3() {
		return value3;
	}

	public void setValue3(String value3) {
		this.value3 = value3;
	}

	public String getValue4() {
		return value4;
	}

	public void setValue4(String value4) {
		this.value4 = value4;
	}

	public String getValue5() {
		return value5;
	}

	public void setValue5(String value5) {
		this.value5 = value5;
	}
}