package com.foya.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema="BT3500", name="FY_TB_TRANSACTION")
@IdClass(com.foya.model.FyTbTransactionId.class)
public class FyTbTransaction {
	@Basic
	@Column(nullable=false, length=50)
	private String address;

	@Basic
	@Column(length=22, scale=6)
	private double amount;

	@Basic
	@Column(name="CR_DATE", columnDefinition="DATE")
	private Date crDate;

	@Basic
	@Column(name="CR_USER", length=40)
	private String crUser;

	@Basic
	@Column(name="CUST_ID", nullable=false, length=10)
	private String custId;

	@Basic
	@Column(columnDefinition="DATE")
	private Date datestamp;

	@Basic
	@Column(name="FILE_SEQ", length=10)
	private long fileSeq;

	@Id
	@Column(name="FILE_TYPE", length=10)
	private String fileType;

	@Id
	@Column(length=200)
	private String filename;

	@Basic
	@Column(length=50)
	private String memo;

	@Basic
	@Column(nullable=false, length=20)
	private String phone;

	@Basic
	@Column(length=20, scale=6)
	private double price;

	@Basic
	@Column(name="PRODUCT_ID", nullable=false, length=10)
	private String productId;

	@Basic
	@Column(name="STORE_ID", nullable=false, length=10)
	private String storeId;

	@Id
	@Column(name="TRANSACTION_SEQ", length=10)
	private long transactionSeq;

	@Basic
	@Column(name="TRANSACTION_TIME", columnDefinition="DATE", nullable=false)
	private Date transactionTime;

	@Basic
	@Column(name="TRANSACTION_TYPE", nullable=false, length=10)
	private String transactionType;

	@Basic
	@Column(length=10)
	private long unit;

	@Basic
	@Column(length=40)
	private String userstamp;


	public FyTbTransaction() {
	}

	public FyTbTransaction(String fileType, String filename, long transactionSeq) {
		this.fileType = fileType;
		this.filename = filename;
		this.transactionSeq = transactionSeq;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public double getAmount() {
		return amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public Date getCrDate() {
		return crDate;
	}

	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	public String getCrUser() {
		return crUser;
	}

	public void setCrUser(String crUser) {
		this.crUser = crUser;
	}

	public String getCustId() {
		return custId;
	}

	public void setCustId(String custId) {
		this.custId = custId;
	}

	public Date getDatestamp() {
		return datestamp;
	}

	public void setDatestamp(Date datestamp) {
		this.datestamp = datestamp;
	}

	public long getFileSeq() {
		return fileSeq;
	}

	public void setFileSeq(long fileSeq) {
		this.fileSeq = fileSeq;
	}

	public String getFileType() {
		return fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	public String getFilename() {
		return filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getStoreId() {
		return storeId;
	}

	public void setStoreId(String storeId) {
		this.storeId = storeId;
	}

	public long getTransactionSeq() {
		return transactionSeq;
	}

	public void setTransactionSeq(long transactionSeq) {
		this.transactionSeq = transactionSeq;
	}

	public Date getTransactionTime() {
		return transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

	public String getTransactionType() {
		return transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	public long getUnit() {
		return unit;
	}

	public void setUnit(long unit) {
		this.unit = unit;
	}

	public String getUserstamp() {
		return userstamp;
	}

	public void setUserstamp(String userstamp) {
		this.userstamp = userstamp;
	}
}