package com.foya.model;

import java.io.*;

/**
 * Application identity class for: com.foya.model.FyTbLookupType
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class FyTbLookupTypeId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("com.foya.model.FyTbLookupType"); }
		catch(Exception e) {}
	}

	public String lookupType;

	public FyTbLookupTypeId() {
	}

	public FyTbLookupTypeId(String str) {
		fromString(str);
	}

	public String getLookupType() {
		return lookupType;
	}

	public void setLookupType(String lookupType) {
		this.lookupType = lookupType;
	}

	public String toString() {
		return lookupType;
	}

	public int hashCode() {
		return ((lookupType == null) ? 0 : lookupType.hashCode());
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		FyTbLookupTypeId other = (FyTbLookupTypeId) obj;
		return ((lookupType == null && other.lookupType == null)
			|| (lookupType != null && lookupType.equals(other.lookupType)));
	}

	private void fromString(String str) {
		if("null".equals(str))
			lookupType = null;
		else
			lookupType = str;
	}
}