package com.foya.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema="BT3500", name="FY_TB_FILE_CNTRL")
@IdClass(com.foya.model.FyTbFileCntrlId.class)
public class FyTbFileCntrl {
	@Basic
	@Column(name="CR_DATE", columnDefinition="DATE")
	private Date crDate;

	@Basic
	@Column(name="CR_USER", length=40)
	private String crUser;

	@Basic
	@Column(columnDefinition="DATE")
	private Date datestamp;

	@Basic
	@Column(length=1024)
	private String dscr;

	@Basic
	@Column(name="END_TIME", columnDefinition="DATE")
	private Date endTime;

	@Basic
	@Column(name="ERROR_COUNT", length=10)
	private long errorCount;

	@Basic
	@Column(name="FILE_SEQ", length=10)
	private long fileSeq;

	@Id
	@Column(name="FILE_TYPE", length=10)
	private String fileType;

	@Id
	@Column(length=200)
	private String filename;

	@Basic
	@Column(name="MAX_TRANSACTION_TIME", columnDefinition="DATE")
	private Date maxTransactionTime;

	@Basic
	@Column(name="MIN_TRANSACTION_TIME", columnDefinition="DATE")
	private Date minTransactionTime;

	@Basic
	@Column(name="START_TIME", columnDefinition="DATE")
	private Date startTime;

	@Basic
	@Column(nullable=false, length=2)
	private String status;

	@Basic
	@Column(name="TOTAL_AMOUNT", length=22, scale=6)
	private double totalAmount;

	@Basic
	@Column(name="TOTAL_COUNT", length=10)
	private long totalCount;

	@Basic
	@Column(length=40)
	private String userstamp;


	public FyTbFileCntrl() {
	}

	public FyTbFileCntrl(String fileType, String filename) {
		this.fileType = fileType;
		this.filename = filename;
	}

	public Date getCrDate() {
		return crDate;
	}

	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	public String getCrUser() {
		return crUser;
	}

	public void setCrUser(String crUser) {
		this.crUser = crUser;
	}

	public Date getDatestamp() {
		return datestamp;
	}

	public void setDatestamp(Date datestamp) {
		this.datestamp = datestamp;
	}

	public String getDscr() {
		return dscr;
	}

	public void setDscr(String dscr) {
		this.dscr = dscr;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public long getErrorCount() {
		return errorCount;
	}

	public void setErrorCount(long errorCount) {
		this.errorCount = errorCount;
	}

	public long getFileSeq() {
		return fileSeq;
	}

	public void setFileSeq(long fileSeq) {
		this.fileSeq = fileSeq;
	}

	public String getFileType() {
		return fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	public String getFilename() {
		return filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public Date getMaxTransactionTime() {
		return maxTransactionTime;
	}

	public void setMaxTransactionTime(Date maxTransactionTime) {
		this.maxTransactionTime = maxTransactionTime;
	}

	public Date getMinTransactionTime() {
		return minTransactionTime;
	}

	public void setMinTransactionTime(Date minTransactionTime) {
		this.minTransactionTime = minTransactionTime;
	}

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public double getTotalAmount() {
		return totalAmount;
	}

	public void setTotalAmount(double totalAmount) {
		this.totalAmount = totalAmount;
	}

	public long getTotalCount() {
		return totalCount;
	}

	public void setTotalCount(long totalCount) {
		this.totalCount = totalCount;
	}

	public String getUserstamp() {
		return userstamp;
	}

	public void setUserstamp(String userstamp) {
		this.userstamp = userstamp;
	}
}