package com.foya.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema="BT3500", name="FY_TB_FILE_INFO")
@IdClass(com.foya.model.FyTbFileInfoId.class)
public class FyTbFileInfo {
	@Basic
	@Column(length=22, scale=6)
	private double amount;

	@Basic
	@Column(length=10)
	private long count;

	@Basic
	@Column(name="CR_DATE", columnDefinition="DATE")
	private Date crDate;

	@Basic
	@Column(name="CR_USER", length=40)
	private String crUser;

	@Basic
	@Column(columnDefinition="DATE")
	private Date datestamp;

	@Basic
	@Column(name="FILE_SEQ", length=10)
	private long fileSeq;

	@Id
	@Column(name="FILE_TYPE", length=10)
	private String fileType;

	@Id
	@Column(length=200)
	private String filename;

	@Id
	@Column(name="TRANSACTION_TYPE", length=10)
	private String transactionType;

	@Basic
	@Column(length=40)
	private String userstamp;


	public FyTbFileInfo() {
	}

	public FyTbFileInfo(String fileType, String filename, String transactionType) {
		this.fileType = fileType;
		this.filename = filename;
		this.transactionType = transactionType;
	}

	public double getAmount() {
		return amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public long getCount() {
		return count;
	}

	public void setCount(long count) {
		this.count = count;
	}

	public Date getCrDate() {
		return crDate;
	}

	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	public String getCrUser() {
		return crUser;
	}

	public void setCrUser(String crUser) {
		this.crUser = crUser;
	}

	public Date getDatestamp() {
		return datestamp;
	}

	public void setDatestamp(Date datestamp) {
		this.datestamp = datestamp;
	}

	public long getFileSeq() {
		return fileSeq;
	}

	public void setFileSeq(long fileSeq) {
		this.fileSeq = fileSeq;
	}

	public String getFileType() {
		return fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	public String getFilename() {
		return filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getTransactionType() {
		return transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	public String getUserstamp() {
		return userstamp;
	}

	public void setUserstamp(String userstamp) {
		this.userstamp = userstamp;
	}
}