package com.foya.model;

import java.io.*;

/**
 * Application identity class for: com.foya.model.FyTbFileInfo
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class FyTbFileInfoId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("com.foya.model.FyTbFileInfo"); }
		catch(Exception e) {}
	}

	public String fileType;
	public String filename;
	public String transactionType;

	public FyTbFileInfoId() {
	}

	public FyTbFileInfoId(String str) {
		fromString(str);
	}

	public String getFileType() {
		return fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	public String getFilename() {
		return filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getTransactionType() {
		return transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	public String toString() {
		return fileType
			+ "::" + filename
			+ "::" + transactionType;
	}

	public int hashCode() {
		int rs = 17;
		rs = rs * 37 + ((fileType == null) ? 0 : fileType.hashCode());
		rs = rs * 37 + ((filename == null) ? 0 : filename.hashCode());
		rs = rs * 37 + ((transactionType == null) ? 0 : transactionType.hashCode());
		return rs;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		FyTbFileInfoId other = (FyTbFileInfoId) obj;
		return ((fileType == null && other.fileType == null)
			|| (fileType != null && fileType.equals(other.fileType)))
			&& ((filename == null && other.filename == null)
			|| (filename != null && filename.equals(other.filename)))
			&& ((transactionType == null && other.transactionType == null)
			|| (transactionType != null && transactionType.equals(other.transactionType)));
	}

	private void fromString(String str) {
		Tokenizer toke = new Tokenizer(str);
		str = toke.nextToken();
		if("null".equals(str))
			fileType = null;
		else
			fileType = str;
		str = toke.nextToken();
		if("null".equals(str))
			filename = null;
		else
			filename = str;
		str = toke.nextToken();
		if("null".equals(str))
			transactionType = null;
		else
			transactionType = str;
	}

	protected static class Tokenizer {
		private final String str;
		private int last;

		public Tokenizer (String str) {
			this.str = str;
		}

		public String nextToken () {
			int next = str.indexOf("::", last);
			String part;
			if(next == -1) {
				part = str.substring(last);
				last = str.length();
			} else {
				part = str.substring(last, next);
				last = next + 2;
			}
			return part;
		}
	}
}