server:
  servlet:
    context-path: /
  port: ${PORT:6060}

### 資料庫連線 配置
spring:
  datasource:
    name: mms
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@10.1.1.205:1521:iotbs
    username: BT3500
    password: BT3500
    initialization-mode: ALWAYS
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      minimum-idle: 5
      max-lifetime: 1800000
      maximum-pool-size: 10      
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false 
    properties:
      hibernate.format_sql : false
      hibernate.dialect: org.hibernate.dialect.Oracle12cDialect
      hibernate.enable_lazy_load_no_trans: true

logging:
  level:
   root: debug        
      
      
